### PR TITLE
Add vhost-user device support (RNG, sound, vsock, CAN, console, input, rtc)

### PR DESCRIPTION
**Pull request by dorindabassey**
Implement vhost-user protocol support in libkrun, enabling out-of-process virtio device backends using rust-vmm/vhost-device.
  ### Key Changes                                                                                         
                  
  - **Core vhost-user infrastructure**: Generic `VhostUserDevice` wrapper, file-backed memory (memfd), config space support
  - **Device support**: RNG, sound, vsock, CAN, console, rtc and input devices                               
  - **API**: `krun_set_vhost_user_device()` with public constants for each device type                   
  - **Examples**: Integration in `chroot_vm` for all supported devices

All devices tested and working with corresponding vhost-device backends.

### CODE REVIEW

File: src/vmm/src/builder.rs [hunk 1]
```diff
@@ -461,6 +467,14 @@ impl Display for StartMicrovmError {
                     "Cannot initialize a MMIO Snd Device or add a device to the MMIO Bus. {err_msg}"
                 )
             }
+            RegisterVhostUserDevice(ref err) => {
+                let mut err_msg = format!("{err}");
```
Comment (bilelmoussaoui) [inline src/vmm/src/builder.rs]: Given that mmio::Error likely implements Display, you could use to_string() here instead of going through format! no?

File: src/vmm/src/builder.rs [hunk 2]
```diff
@@ -1331,9 +1367,79 @@ fn load_payload(
                     return Err(StartMicrovmError::MissingKernelConfig);
                 };
 
-            let kernel_region = unsafe {
-                MmapRegion::build_raw(kernel_host_addr as *mut u8, kernel_size, 0, 0)
-                    .map_err(StartMicrovmError::InvalidKernelBundle)?
+            #[cfg(all(feature = "vhost-user", target_os = "linux"))]
```
Comment (bilelmoussaoui) [inline src/vmm/src/builder.rs:1369]: I guess you could have put this cfg above a scope defined with `{}` so you don't need to repeat it multiple times?

File: src/vmm/src/builder.rs [hunk 3]
```diff
@@ -1502,10 +1608,74 @@ pub fn create_guest_memory(
             .map_err(StartMicrovmError::ShmCreate)?;
     }
 
+    // For vhost-user devices, we need file-backed memory so the backend can mmap it
+    #[cfg(all(feature = "vhost-user", target_os = "linux"))]
```
Comment (bilelmoussaoui) [inline src/vmm/src/builder.rs:1605]: Same here

File: src/vmm/src/builder.rs [hunk 4]
```diff
@@ -1502,10 +1608,74 @@ pub fn create_guest_memory(
...
+            debug!(
+                "Creating file-backed memory for vhost-user (regions: {})",
+                arch_mem_regions.len()
+            );
+            // Create file-backed memory regions using memfd
+            let regions_with_files: Vec<_> = arch_mem_regions
+                .iter()
+                .map(|(addr, size)| {
+                    debug!(
+                        "  Creating memfd for region: addr=0x{:x}, size=0x{:x}",
```
Comment (bilelmoussaoui) [inline src/vmm/src/builder.rs]:
```suggestion
                        "Creating memfd for region: addr=0x{:x}, size=0x{:x}",
```

File: src/vmm/src/builder.rs [hunk 5]
```diff
@@ -1502,10 +1608,74 @@ pub fn create_guest_memory(
...
+                        addr.0, size
+                    );
+                    // SAFETY: memfd_create is called with a valid null-terminated C string and valid flags.
+                    // File descriptor ownership is transferred to File::from_raw_fd below.
+                    let memfd = unsafe {
+                        let fd = libc::memfd_create(
+                            b"guest_mem\0".as_ptr() as *const libc::c_char,
```
Comment (bilelmoussaoui) [inline src/vmm/src/builder.rs]: You can use c"" nowadays no?

File: src/vmm/src/builder.rs [hunk 6]
```diff
@@ -1502,10 +1608,74 @@ pub fn create_guest_memory(
...
+                        }
+                        if libc::ftruncate(fd, *size as i64) < 0 {
+                            error!(
+                                "Failed to ftruncate memfd: {:?}",
+                                io::Error::last_os_error()
+                            );
+                            libc::close(fd);
+                            return Err(io::Error::last_os_error());
+                        }
+                        debug!("  Created memfd with fd={}", fd);
```
Comment (bilelmoussaoui) [inline src/vmm/src/builder.rs]:
```suggestion
                        debug!("Created memfd with fd={}", fd);
```

File: src/devices/src/virtio/vhost_user/device.rs [hunk 7]
```diff
@@ -0,0 +1,591 @@
...
+    /// * `device_type` - Virtio device type ID
+    /// * `device_name` - Human-readable device name for logging
+    /// * `num_queues` - Number of queues (0 = query backend via MQ protocol)
+    /// * `queue_sizes` - Size for each queue (empty = use default 256)
+    ///
+    /// # Returns
+    ///
+    /// A new VhostUserDevice or an error if connection fails.
+    pub fn new(
+        socket_path: &str,
```
Comment (bilelmoussaoui) [inline src/devices/src/virtio/vhost_user/device.rs]: an actual Path maybe?

File: src/devices/src/virtio/vhost_user/device.rs [hunk 8]
```diff
@@ -0,0 +1,591 @@
...
+
+        let default_size = queue_sizes.last().copied().unwrap_or(256);
+        let queue_configs: Vec<_> = (0..actual_num_queues)
+            .map(|i| {
+                let size = queue_sizes.get(i).copied().unwrap_or(default_size);
+                QueueConfig::new(size)
+            })
+            .collect();
+
+        Ok(VhostUserDevice {
```
Comment (bilelmoussaoui) [inline src/devices/src/virtio/vhost_user/device.rs]:
```suggestion
        Ok(Self {
```

**Review by bilelmoussaoui — COMMENTED** [review]
various comments

File: src/vmm/src/builder.rs (hunk 2 above)
Comment (dorindabassey) [reply src/vmm/src/builder.rs:1369]: The cfg repetition is intentional to ensure both branches compile cleanly.

**Comment by dorindabassey** [comment]
Thanks for the reviews @bilelmoussaoui! 
Since this PR builds on several other pending PRs, I'll address all the feedback here in #642 to avoid rebase churn.

File: include/libkrun.h [hunk 9]
```diff
@@ -747,6 +747,123 @@ int krun_add_input_device_fd(uint32_t ctx_id, int input_fd);
...
+ *
+ * Returns:
+ *  Zero on success or a negative error number on failure.
+ *  -EINVAL  - Invalid parameters (device_type, socket_path, etc.)
+ *  -ENOENT  - Context doesn't exist
+ *  -ENOTSUP - vhost-user support not compiled in
+ */
+int32_t krun_add_vhost_user_device(uint32_t ctx_id,
+                                   uint32_t device_type,
+                                   const char *socket_path,
```
Comment (ggoodman) [inline include/libkrun.h:862]: Does this need to be a _path_ at the API level? What if we already have a file descriptor?

Comment (mtjhrc) [reply include/libkrun.h:862]: Fair, we should probably support that, but this is not really an issue blocking the current PR really, this is getting merged into main which is now libkrun 2.x branch. Every public API function is about to get replaced.  #634

File: src/utils/Cargo.toml [hunk 10]
```diff
@@ -12,11 +12,11 @@ bitflags = "1.2.0"
 libc = ">=0.2.85"
 log = "0.4.0"
 nix = "0.30.1"
-vmm-sys-util = "0.14"
+vmm-sys-util = "0.15"
```
Comment (mtjhrc) [inline src/utils/Cargo.toml]: Btw why was this upgraded? The commit message doesn't mention it, though I have no objections to the bump itself.

It seems this is why the CI is failing. This upgraded the dependency here but didn't regenerate the Cargo.lock in the gui-vm example, which also uses this crate. [^1]

[^1]: Maybe it shouldn't use it since is not public API but it does... On the other hand the gui-vm is like a test/reference implementation and not something we actively publish, so it's fine.

Comment (mtjhrc) [reply src/utils/Cargo.toml]: Actaully the version bump also broke the TDX it seems:
```
error[E0308]: mismatched types
   --> src/vmm/src/linux/tee/inteltdx.rs:28:33
    |
 28 |         launcher.init_vm(&caps, cpuid).map_err(Error::InitVm)?;
    |                  -------        ^^^^^ expected `FamStructWrapper<kvm_cpuid2>`, found a different `FamStructWrapper<kvm_cpuid2>`
    |                  |
    |                  arguments to this method are incorrect
    |
note: there are multiple different versions of crate `vmm_sys_util` in the dependency graph
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/vmm-sys-util-0.14.0/src/fam.rs:164:1
    |
164 | pub struct FamStructWrapper<T: Default + FamStruct> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this is the expected type
    |
```

Comment (dorindabassey) [reply src/utils/Cargo.toml]: This issue was introduced in commit https://github.com/containers/libkrun/pull/588/changes/8b5f1fa48168c118f7d77c4a4eb9b522661da755 from PR #588, which upgraded to vm-memory 0.17.
There's a dependency incompatibility between the vhost crate and TDX requirements.
- vhost 0.14 requires vm-memory 0.16 + vmm-sys-util 0.14 (TDX works here) which means reverting the commit https://github.com/containers/libkrun/pull/588/changes/8b5f1fa48168c118f7d77c4a4eb9b522661da755 
- vhost 0.15/0.16 requires vm-memory 0.17 + vmm-sys-util 0.15 (correct vm-memory but breaks TDX because TDX requires vmm-sys-util 0.14)

To resolve this, we need either:
  1. Update TDX dependencies to work with vmm-sys-util 0.15, or                                          
  2. Temporarily pin to vm-memory 0.16 until upstream dependencies align.

Comment (dorindabassey) [reply src/utils/Cargo.toml]: fixed it by adding vmm-sys-util 0.15 as optional dependency for vhost-user feature, and converted EventFd types when calling `set_vring_kick`/`set_vring_call` so we don't have to wait for upstream dep updates.

**Review by mtjhrc — DISMISSED** [review]
LGTM, thanks! 

Code LGTM. I've only tested Sound and Vsock specifically now (and NET before which is not in the list of "officially" supported devices yet).

File: src/devices/src/virtio/vhost_user/device.rs [hunk 11]
```diff
@@ -0,0 +1,558 @@
...
+
+        // Unregister activate_evt as it's only needed once
+        event_manager
+            .unregister(self.activate_evt.as_raw_fd())
+            .unwrap_or_else(|e| {
+                error!(
+                    "{}: failed to unregister activate event: {e:?}",
+                    self.device_name
+                );
+            });
```
Comment (mtjhrc) [inline src/devices/src/virtio/vhost_user/device.rs:561]: This is not really correct, you will miss registering the file descriptors on second activate() call after reset. But It still wouldn't work even if you removed the highlighted portion since the `VHOST_USER_PROTOCOL_F_RESET_DEVICE` is not implemented - the implemented `fn reset()` only works as a shutdown but not as an actual reset. 

Reset is a general problem in other libkrun devices too and is half-borked everywhere, there are also some unfinished things in our mmio transport layer implementation, so we should probably address that more generally first before implementing the vhost reset here. [^1]  [^2] [^3]

No change needed for now, I just wanted to point out the limitation which is not obvious. 

[^1]: https://github.com/containers/libkrun/pull/631#issuecomment-4237384774
[^2]: https://github.com/mtjhrc/libkrun/blob/e12b9b3780ffa8df9f3e1797b217d13453479167/src/devices/src/virtio/mmio.rs#L295-L296
[^3]: https://github.com/mtjhrc/libkrun/blob/e12b9b3780ffa8df9f3e1797b217d13453479167/src/devices/src/virtio/mmio.rs#L352-L353

**Review by slp — APPROVED** [review]
vhost-user support let's gooooo!

thanks @dorindabassey

**Comment by ggoodman** [comment]
Do you imagine extending this to vhost-user-fs devices?
