### ISSUE TITLE
make SND=1 fails on pipewire 1.6 with: error[E0609]: no field `data` on type `spa_pod_builder`

### ISSUE THREAD

**Issue by svenstaro** [containers/libkrun#650]
Hey, release v1.18.0 doesn't build for me:
```
export ZSTD_SYS_USE_PKG_CONFIG=1
make BLK=1 NET=1 EFI=0 GPU=1 SND=1 INPUT=1 VERBOSE=1
...
Compiling krun-input v0.1.0 (/build/libkrun/src/libkrun-1.18.0/src/input)
   Compiling krun-display v0.1.0 (/build/libkrun/src/libkrun-1.18.0/src/display)
error[E0609]: no field `data` on type `spa_pod_builder`
  --> /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libspa-0.8.0/src/pod/builder.rs:38:25
   |
38 |         (*this).builder.data = (*this).data.as_mut_ptr().cast::<c_void>();
   |                         ^^^^ unknown field
   |
   = note: available field is: `_address`

error[E0609]: no field `size` on type `spa_pod_builder`
  --> /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libspa-0.8.0/src/pod/builder.rs:39:25
   |
39 |         (*this).builder.size = (*this)
   |                         ^^^^ unknown field
   |
   = note: available field is: `_address`

For more information about this error, try `rustc --explain E0609`.
error: could not compile `libspa` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:207: target/release/libkrun.so.1.18.0] Error 101
```

**Comment by svenstaro** [comment]
I investigated this and it should work on libspa 0.9. They changed the API a bit so it's not a trivial upgrade. I will try to produce a patch.
